name: code quality

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: cachix/install-nix-action@v31.10.7

      - name: Build frontend
        run: nix develop -c bash -c 'cd web && pnpm install --frozen-lockfile && pnpm build'

      - name: Run golangci-lint
        run: nix develop -c golangci-lint run --timeout=5m
