name: update gomod2nix

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go.mod
          cache: true

      - id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update gomod2nix metadata
        run: go run github.com/nix-community/gomod2nix@v1.7.0 generate

      - uses: peter-evans/create-pull-request@v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: update-gomod2nix
          commit-message: update gomod2nix metadata
          title: update gomod2nix metadata
